i think we're done?

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -102,20 +102,11 @@ jobs:
           ret="${ret//$'\r'/'%0A'}"
           echo "::set-output name=ret::$ret"
 
-      # - name: print returncode
-        # run: |
-          # echo "Returncode is ${{ steps.get-returncode.outputs.ret }}"
-
       - name: return 5 for incomplete packages
         if: "contains(steps.get-returncode.outputs.ret, '5')"
         run: |
-          echo '5'
+          echo 'exiting with 5 for incomplete packages'
           exit 5
-
-      - name: return 1 for incomplete packages
-        if: "contains(steps.get-returncode.outputs.ret, '1')"
-        run: |
-          echo '1'
 
       - id: get-comment-body
         run: |
@@ -132,3 +123,8 @@ jobs:
           body: ${{ steps.get-comment-body.outputs.body }}
           comment-author: 'Phylum[bot]'
 
+      - name: return 1 for risk analysis failure
+        if: "contains(steps.get-returncode.outputs.ret, '1')"
+        run: |
+          echo 'exiting with 1 for risk analysis failure'
+          exit 1
